import Cocoa
import WebKit

// MarkedJS.swift (generated by build.sh) provides markedJSBase64
let markedJS = String(data: Data(base64Encoded: markedJSBase64)!, encoding: .utf8)!

let css = """
:root { color-scheme: light dark; }
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
  font-size: 15px; line-height: 1.6;
  max-width: 780px; margin: 0 auto; padding: 32px 24px 64px;
  color: #1f2328; background: #ffffff;
  word-wrap: break-word;
}
h1, h2 { border-bottom: 1px solid #d1d9e0; padding-bottom: .3em; }
h1, h2, h3, h4, h5, h6 { margin-top: 24px; margin-bottom: 16px; font-weight: 600; line-height: 1.25; }
a { color: #0969da; text-decoration: none; }
a:hover { text-decoration: underline; }
code, pre {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 85%;
  background: #f0f1f3;
  border-radius: 6px;
}
code { padding: .2em .4em; }
pre { padding: 16px; overflow-x: auto; line-height: 1.45; }
pre code { padding: 0; background: none; }
blockquote { margin: 0 0 16px; padding: 0 1em; color: #59636e; border-left: .25em solid #d1d9e0; }
table { border-collapse: collapse; margin-bottom: 16px; display: block; overflow-x: auto; }
th, td { border: 1px solid #d1d9e0; padding: 6px 13px; }
th { font-weight: 600; }
tr:nth-child(2n) { background: #f6f8fa; }
img { max-width: 100%; }
hr { border: 0; border-top: 1px solid #d1d9e0; margin: 24px 0; }
ul, ol { padding-left: 2em; }
li + li { margin-top: .25em; }
@media (prefers-color-scheme: dark) {
  body { color: #f0f6fc; background: #0d1117; }
  h1, h2 { border-color: #3d444d; }
  a { color: #4493f8; }
  code, pre { background: #161b22; }
  blockquote { color: #9198a1; border-color: #3d444d; }
  th, td { border-color: #3d444d; }
  tr:nth-child(2n) { background: #151b23; }
  hr { border-color: #3d444d; }
}
"""

class AppDelegate: NSObject, NSApplicationDelegate, NSWindowDelegate {
    var window: NSWindow!
    var webView: WKWebView!
    var fileURL: URL
    var watcher: DispatchSourceFileSystemObject?
    var watchedFD: Int32 = -1

    init(fileURL: URL) {
        self.fileURL = fileURL
        super.init()
    }

    func applicationDidFinishLaunching(_ notification: Notification) {
        let frame = NSRect(x: 0, y: 0, width: 820, height: 900)
        window = NSWindow(
            contentRect: frame,
            styleMask: [.titled, .closable, .miniaturizable, .resizable],
            backing: .buffered, defer: false)
        window.title = fileURL.lastPathComponent
        window.center()
        window.delegate = self
        window.setFrameAutosaveName("mdreader")

        webView = WKWebView(frame: frame)
        webView.autoresizingMask = [.width, .height]
        window.contentView = webView

        render(restoreScroll: false)
        startWatching()

        window.makeKeyAndOrderFront(nil)
        NSApp.activate(ignoringOtherApps: true)
    }

    func render(restoreScroll: Bool) {
        guard let data = try? Data(contentsOf: fileURL) else { return }
        let mdBase64 = data.base64EncodedString()
        let scrollJS = restoreScroll
            ? "window.scrollTo(0, sessionStorage.getItem('y') || 0);"
            : ""
        let html = """
        <!doctype html><html><head><meta charset="utf-8">
        <style>\(css)</style>
        <script>\(markedJS)</script>
        </head><body><div id="content"></div>
        <script>
        const bytes = Uint8Array.from(atob("\(mdBase64)"), c => c.charCodeAt(0));
        const md = new TextDecoder('utf-8').decode(bytes);
        document.getElementById('content').innerHTML = marked.parse(md);
        \(scrollJS)
        addEventListener('scroll', () => sessionStorage.setItem('y', window.scrollY));
        </script></body></html>
        """
        webView.loadHTMLString(html, baseURL: fileURL.deletingLastPathComponent())
    }

    func startWatching() {
        stopWatching()
        watchedFD = open(fileURL.path, O_EVTONLY)
        guard watchedFD >= 0 else { return }
        let source = DispatchSource.makeFileSystemObjectSource(
            fileDescriptor: watchedFD,
            eventMask: [.write, .delete, .rename],
            queue: .main)
        source.setEventHandler { [weak self] in
            guard let self else { return }
            let events = source.data
            // Editors often replace the file (rename/delete) — re-open the watch
            if events.contains(.delete) || events.contains(.rename) {
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                    self.render(restoreScroll: true)
                    self.startWatching()
                }
            } else {
                self.render(restoreScroll: true)
            }
        }
        source.setCancelHandler { [fd = watchedFD] in close(fd) }
        source.resume()
        watcher = source
    }

    func stopWatching() {
        watcher?.cancel()
        watcher = nil
        watchedFD = -1
    }

    func windowWillClose(_ notification: Notification) {
        NSApp.terminate(nil)
    }

    @objc func reload(_ sender: Any?) {
        render(restoreScroll: true)
    }
}

func buildMenu() -> NSMenu {
    let main = NSMenu()
    let appItem = NSMenuItem()
    main.addItem(appItem)
    let appMenu = NSMenu()
    appItem.submenu = appMenu
    appMenu.addItem(withTitle: "Quit mdreader", action: #selector(NSApplication.terminate(_:)), keyEquivalent: "q")

    let fileItem = NSMenuItem()
    main.addItem(fileItem)
    let fileMenu = NSMenu(title: "File")
    fileItem.submenu = fileMenu
    fileMenu.addItem(withTitle: "Reload", action: #selector(AppDelegate.reload(_:)), keyEquivalent: "r")
    fileMenu.addItem(withTitle: "Close", action: #selector(NSWindow.performClose(_:)), keyEquivalent: "w")

    let editItem = NSMenuItem()
    main.addItem(editItem)
    let editMenu = NSMenu(title: "Edit")
    editItem.submenu = editMenu
    editMenu.addItem(withTitle: "Copy", action: #selector(NSText.copy(_:)), keyEquivalent: "c")
    editMenu.addItem(withTitle: "Select All", action: #selector(NSText.selectAll(_:)), keyEquivalent: "a")
    return main
}

// --- entry point ---
let args = CommandLine.arguments
var url: URL

if args.count > 1 {
    url = URL(fileURLWithPath: (args[1] as NSString).expandingTildeInPath)
} else {
    let app = NSApplication.shared
    app.setActivationPolicy(.regular)
    let panel = NSOpenPanel()
    panel.allowedContentTypes = [.init(filenameExtension: "md")!, .init(filenameExtension: "markdown")!]
    panel.message = "Choose a Markdown file"
    guard panel.runModal() == .OK, let chosen = panel.url else { exit(0) }
    url = chosen
}

guard FileManager.default.fileExists(atPath: url.path) else {
    FileHandle.standardError.write("mdreader: no such file: \(url.path)\n".data(using: .utf8)!)
    exit(1)
}

let app = NSApplication.shared
app.setActivationPolicy(.regular)
let delegate = AppDelegate(fileURL: url)
app.delegate = delegate
app.mainMenu = buildMenu()
app.run()
